murrine
murrine-themes
gtk-engines
gtk-engines-unico
LX-Colors-themes
LX-Colors-Revival
cantarell-fonts
boje-themes
bunsen-themes
cathexis-suite-themes
clearlooks-classic-themes
clearlooks-phenix-theme
gnome-themes-extras
moka-themes
siva-flat-themes
Alphacube-GTK
numix-gtk-theme
orchis-gtk-theme
paper-gtk-theme
vivacious-colors-gtk-theme
awoken-icon-theme
faba-icon-theme
faba-mono-icons
faenza-icon-theme
faenza-xfce
kfaenza-icon-theme
faience-icon-theme
meliae-icon-theme
moka-icon-theme
p7zip
moka-minimal
numix-icon-theme
numix-icon-theme-bevel
numix-icon-theme-circle
vivacious-colors-gtk-icon-theme
